site_name: Challenge 1 - Megatron

theme:
  name: material

repo_url: https://github.com/unb-Sistemas-de-Machine-learning/challenge_1_megatron

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Arquitetura: arquitetura.md
  - Fontes de Dados: dados.md
  - Guiding Questions: guiding-questions.md
  - Canvas: canva.md