site_name: Challenge 1 - Megatron

theme:
  name: material

repo_url: https://github.com/unb-Sistemas-de-Machine-learning/challenge_1_megatron

markdown_extensions:
  - admonition

nav: 
  - Home: index.md
  - Guiding Questions: guiding-questions.md
  - Canvas: canva.md