#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose-v2
swap:
  filename: /swapfile
  size: 2G
  maxsize: 2G
runcmd:
  - usermod -aG docker vof
  - systemctl enable --now docker
